apiVersion: v1
kind: Service
metadata:
  name: {{ include "predicate.fullname" . }}
  annotations:
    {{- tpl (toYaml .Values.service.annotations | nindent 4) $ }}
  labels:
    {{- include "predicate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
{{- end }}
  selector:
    {{- include "predicate.selectorLabels" . | nindent 4 }}
