# Default values for witnesschain-watchtower.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of for `app` labels
##
nameOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

## Common labels
##
commonLabels: {}

## Annotations
##
annotations: {}

## Number of replicas
##
replicas: 1

## Network to which the client is connected
network: holesky

## Affinity configuration for pods
##
affinity: {}

## Tolerations for pods
##
tolerations: []

## Security context for pods
##
securityContext:
  runAsUser: 65534
  runAsGroup: 65534

## Security context for containers
##
containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true

## Node selector for pods
##
nodeSelector: {}

## Resource requests and limits
##
resources: {}

## Image pull secrets for docker images
##
imagePullSecrets: []

## Image of witnesschain watchtower
##
image:
  ## Watchtower container image repository
  ##
  repository: witnesschain/infinity-watch

  ## Watchtower container iamge tag
  ##
  tag: latest

  ## Watchtower container pull policy
  ##
  pullPolicy: IfNotPresent

## Liveness probe
##
livenessProbe:
  httpGet:
    port: metrics
    path: /metrics
  initialDelaySeconds: 60
  periodSeconds: 120

## Readiness probe
##
readinessProbe:
  httpGet:
    port: metrics
    path: /metrics
  initialDelaySeconds: 30
  periodSeconds: 10

## Metrics Port
##
metricsPort: 9090

## Service configuration
##
service:
  ## Service type
  ##
  type: ClusterIP

  ## LoadBalancer IP
  ##
  loadBalancerIP: ""

  ## External traffic policy
  ##
  externalTrafficPolicy: Cluster

  ## Service ports
  ##
  ports:
    - 11112
    - 22223
    - 33334
    - 33335
    - 33336
    - 44445
    - 44446
    - 44447
    - 55556

## Service account to use
##
serviceAccount:
  ## Specifies whether a service account should be created
  ##
  create: false

  ## Name of the service account to use
  ##
  name: ""

## Service monitor to use
##
serviceMonitor:
  ## If true, create a serviceMonitor
  ##
  enabled: true

  ## Path to scrape
  ##
  path: /metrics

  ## Scrape interval
  ##
  interval: 1m

  ## Scrape timeout
  ##
  scrapeTimeout: 30s

## Secrets for watchtower
##
secrets:
  ## Secret name for watchtower key
  ##
  watchtowerKey: ""

## Watchtower client configuration
## https://docs.witnesschain.com/infinity-watch/proof-of-location-mainnet/run-a-watchtower/eigenlayer-operators/running-a-pol-watchtower#id-2.-setting-up-the-watchtower
env:
  #latitude: 37.01511676489697
  #longitude: -79.0392271449855
  radius: 1000
  keyType: ethereum
  saveResultsInDatabase: false
  submitResultsToContract: false
  rpcUrl: https://rpc.witnesschain.com
  projectName: "eigenlayer-A41"
  walletPublicKey: "<operator_public_address>"