nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000
securityContext: {}

commonLabels: {}

imagePullSecrets: []
service:
  labels: {}
  annotations: {}
  type: ClusterIP
  ports:
    - name: metrics
      port: 9094
      protocol: TCP
      targetPort: metrics
ingress:
  annotations: {}
  enabled: false
  host: example.com

serviceMonitor:
  enabled: true
  interval: 30s
  ports:
    - name: metrics
      path: /metrics

configs:
  mach-config.toml: |
    ##############################################
    # Mach alerter configuration                 #
    ##############################################
    [alerter]
    # Only print the warning log if the alerter is disabled,
    # Otherwise the alerts will be sent to the Mach AVS Operator
    # Optional, default value: false
    enable = true
    # The JSONRPC endpoint of Mach AVS Operator
    url = "http://127.0.0.1:8901"

    ##############################################
    # Mach validator configuration               #
    ##############################################
    [validator]
    # Validate mode: "unsafe", "safe", "strict"
    #
    # "unsafe": Don't execute EVM, return ok directly.
    # "safe": Execute EVM ，return ok regardless of whether it's right or wrong.
    # "strict": Execute EVM, return the execution result.
    #
    # Optional, default value: "unsafe"
    mode = "unsafe"
    # The rate limit of rpc request
    # Optional, default value: 100ms
    rpc_rate_ms = 100

    ##############################################
    # Mach fetcher configuration                 #
    ##############################################
    [fetcher]
    # The JSONRPC endpoint of Optimism node
    url = ""
    # The interval (milliseconds) for fetching finalized/latest block of Optimism node
    # Optional, default value: 1000ms
    interval_ms = 4000

    ##############################################
    # Mach scheduler configuration               #
    ##############################################
    [scheduler]
    # The timeout waiting for verify result.
    # If it times out, the verify result will be checked again in the next tick.
    # Optional, default value: 100ms
    verify_timeout_ms = 100

    ##############################################
    # Mach prometheus configuration              #
    ##############################################
    [prometheus]
    # The TCP port of Prometheus exporter
    # Optional, default value: 9094
    port = 9094
    # The HTTP URI path for fetching Prometheus metrics
    # Optional, default value: "/metrics"
    metrics_path = "/metrics"
    # The indication if expose Prometheus exporter on all interfaces
    # true: listen address = "0.0.0.0:port"
    # false: listen address = "127.0.0.1:port"
    # Optional, default value: false
    external = true
  genesis.json: |
    {}
verifier:
  command: []
  ports:
    - containerPort: 9094
      protocol: TCP
      name: metrics
  resources:
    limits:
      cpu: 800m
      memory: 2Gi
    requests:
      cpu: 800m
      memory: 2Gi
  image:
    repository: public.ecr.aws/altlayer/mach
    pullPolicy: Always
    tag: "v0.2.1"
  args:
    - --config=/app/mach-config.toml
    - --genesis-config=/app/genesis.json

  env:
    - name: RUST_LOG
      value: "info"
  startupProbe:
    httpGet:
      path: /metrics
      port: 9094
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /metrics
      port: 9094
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    httpGet:
      path: /metrics
      port: 9094
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 3
    failureThreshold: 2
    successThreshold: 1
nodeSelector: {}

tolerations: []

affinity: {}
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000