apiVersion: v1
kind: Service
metadata:
  name: {{ include "openlayer.fullname" . }}-headless
  labels:
    {{- include "openlayer.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
{{- range .Values.internalService.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
{{- end }}
  selector:
    {{- include "openlayer.selectorLabels" . | nindent 4 }}
