apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lagrange-worker.fullname" . }}-config
  labels:
    {{- include "lagrange-worker.labels" . | nindent 4 }}
data:
  worker-conf.toml: |
    {{- .Values.worker.configToml | nindent 4 }}
