apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagrange-worker.fullname" . }}
  labels:
    {{- include "lagrange-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
  selector:
    {{- include "lagrange-worker.selectorLabels" . | nindent 4 }}
