apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagrange-worker.fullname" . }}-headless
  labels:
    {{- include "lagrange-worker.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "lagrange-worker.selectorLabels" . | nindent 4 }}