apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lagrange-worker.fullname" . }}
  labels:
    {{- include "lagrange-worker.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "lagrange-worker.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "lagrange-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lagrange-worker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lagrange-worker.serviceAccountName" . }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{  .Values.worker.image.tag  }}"
          env:
            {{- range $key, $value := .Values.worker.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: NETWORK
              value: {{ .Values.network }}
            - name: AVS__LAGR_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "lagrange-worker.name" . }}-secrets
                  key: {{ .Values.secretNames.lagrPwdKey }}
            - name: AVS__LAGR_KEYSTORE
              value: "/config/lagr_keystore.json"
          ports:
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: worker-conf
              mountPath: /config/worker-conf.toml
              subPath: worker-conf.toml
            - name: lagr-keystore
              mountPath: /config/lagr_keystore.json
              subPath: lagr_keystore.json
            - name: zkmr-params
              mountPath: /zkmr_params
          command: ["worker", "--config", "/config/worker-conf.toml"]
        # - name: watchtower
        #   image: "{{ .Values.watchtower.image.repository }}:{{ .Values.watchtower.image.tag }}"
        #   args:
        #     {{- toYaml .Values.watchtower.command | nindent 12 }}
        #   volumeMounts:
        #     - name: docker-sock
        #       mountPath: /var/run/docker.sock
      volumes:
        - name: worker-conf
          configMap:
            name: {{ include "lagrange-worker.fullname" . }}-config
        - name: lagr-keystore
          secret:
            secretName: {{ include "lagrange-worker.name" . }}-secrets
            items:
              - key: {{ .Values.secretNames.lagrKeystoreKey }}
                path: lagr_keystore.json
        # - name: docker-sock
        #   hostPath:
        #     path: /var/run/docker.sock
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.config.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.config.size }}
    - metadata:
        name: zkmr-params
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.zkmr_params.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.zkmr_params.size }}
