apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lagrange-worker.fullname" . }}
  labels:
    {{- include "lagrange-worker.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "lagrange-worker.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "lagrange-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lagrange-worker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lagrange-worker.serviceAccountName" . }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.worker.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: NETWORK
              value: {{ .Values.network }}
            - name: AVS__LAGR_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.ecdsaKeystorePassword }}
                  key: password
            - name: AVS__LAGR_KEYSTORE
              value: "/config/lagr_keystore.json"
          ports:
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: worker-conf
              mountPath: /config/worker-conf.toml
              subPath: worker-conf.toml
            - name: lagr-ecdsa-keystore
              mountPath: /config/lagr_keystore.json
              subPath: lagr_keystore.json
            - name: zkmr-params
              mountPath: /zkmr_params
          command: ["worker", "--config", "/config/worker-conf.toml"]
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: config
          emptyDir: {}
        - name: worker-conf
          configMap:
            name: {{ include "lagrange-worker.fullname" . }}-config
        - name: lagr-ecdsa-keystore
          secret:
            secretName: {{ .Values.secrets.ecdsaKeystore }}
            items:
              - key: keystore
                path: lagr_keystore.json
  volumeClaimTemplates:
    - metadata:
        name: zkmr-params
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.zkmr_params.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.zkmr_params.size }}
