{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecrets.attesterPrivateKey.name }}
spec:
  encryptedData:
    privateKey: {{ .Values.sealedSecrets.attesterPrivateKey.value }}
{{- end }}