# 1. META
# 2. SERVICE
# 3. SERVICE ACCOUNT
# 4. INGRESS
# 5. CONTAINER VALUES
# 6. CONFIGS
# 7. SECRETS

# META 
nameOverride: ""
fullnameOverride: ""
replicaCount: 1
labels: {}
imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podSecurityContext: ""
securityContext: ""

# SERVICE
service:
  annotations: {}
  type: ClusterIP
  ports: #외부 노출할 포트 (internal cluster)
    - name: node-api
      port: 9010
      protocol: TCP
      targetPort: 9010
    - name: eigen-metrics
      port: 9090
      protocol: TCP
      targetPort: 9092
    - name: verifier-metrics
      port: 9094
      protocol: TCP
      targetPort: 9094

# ports:
#   - containerPort: 9010
#     protocol: TCP
#   - containerPort: 9090
#     protocol: TCP
#   - containerPort: 9094
#     protocol: TCP

# SERVICE ACCOUNT
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 2000
  securityContext:
    runAsUser: 1000
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # 

# INGRESS
ingress:
  annotations: {}
  enabled: false
  # host: example.com

# CONTAINER VALUES
# CONTAINER - NODE
node:
  image:
    repository: public.ecr.aws/altlayer/mach-operator
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi
  ports:
    - name: eigen-metrics
      port: 9092
      protocol: TCP
      targetPort: 9092
  env:
    - name: OPERATOR_BLS_KEY_PASSWORD
      value: "" ## DONT PUT PASSWORK HERE! SHOULE BE REFERRED FROM SECRET
  startupProbe: ""
  readinessProbe:
    httpGet:
      path: /metrics
      port: 9090
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    httpGet:
      path: /metrics
      port: 9090
    initialDelaySeconds: 1200
    periodSeconds: 30
    timeoutSeconds: 3
    failureThreshold: 2
    successThreshold: 1
  lifecycleHooks: ""

# CONTAINER - VERIFIER
verifier:
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi
  image:
    repository: public.ecr.aws/altlayer/mach
    pullPolicy: IfNotPresent
    tag: "latest"
  ports:
    - name: verifier-metrics
      port: 9094
      protocol: TCP
      targetPort: 9094
  args:
    - --config=/app/mach-config.toml
    - --genesis-config=/app/genesis.json
  env:
    - name: RUST_LOG
      value: "info"
  startupProbe: ""
  readinessProbe:
    httpGet:
      path: /metrics
      port: 9094
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    httpGet:
      path: /metrics
      port: 9094
    initialDelaySeconds: 1200
    periodSeconds: 30
    timeoutSeconds: 3
    failureThreshold: 2
    successThreshold: 1
  lifecycleHooks: ""

# CONFIGS
configs:
  genesis.json: |
    {
      "config": {
        "chainId": 11155420,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "muirGlacierBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "arrowGlacierBlock": 0,
        "grayGlacierBlock": 0,
        "mergeNetsplitBlock": 0,
        "bedrockBlock": 0,
        "regolithTime": 0,
        "terminalTotalDifficulty": 0,
        "terminalTotalDifficultyPassed": true,
        "optimism": {
          "eip1559Elasticity": 6,
          "eip1559Denominator": 50
        }
      },
      "nonce": "0x0",
      "timestamp": "0x64d6dbac",
      "extraData": "0x424544524f434b",
      "gasLimit": "0x1c9c380",
      "difficulty": "0x0",
      "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "coinbase": "0x4200000000000000000000000000000000000011",
      "alloc": {},
      "number": "0x0",
      "gasUsed": "0x0",
      "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "baseFeePerGas": "0x3b9aca00"
    }
  mach-config.toml: |
    ##############################################
    # Mach alerter configuration                 #
    ##############################################
    [alerter]
    # Only print the warning log if the alerter is disabled,
    # Otherwise the alerts will be sent to the Mach AVS Operator
    # Optional, default value: false
    enable = true
    # The JSONRPC endpoint of Mach AVS Operator
    url = "http://mach-avs-holesky-op-sepolia-operator-node:8901"

    ##############################################
    # Mach validator configuration               #
    ##############################################
    [validator]
    # Validate mode: "unsafe", "safe", "strict"?
    #
    # "unsafe": Don't execute EVM, return ok directly.
    # "safe": Execute EVM ，return ok regardless of whether it's right or wrong.
    # "strict": Execute EVM, return the execution result.
    #
    # Optional, default value: "unsafe"
    mode = "unsafe"
    # The rate limit of rpc request
    # Optional, default value: 100ms
    rpc_rate_ms = 100

    ##############################################
    # Mach fetcher configuration                 #
    ##############################################
    [fetcher]
    # The JSONRPC endpoint of Optimism node
    url = "https://rpc.ankr.com/optimism_sepolia/f3b984c11100438aa3242e00b42f8022dfa03bd3163a5f7f394b4e3aa11734d0"
    # The interval (milliseconds) for fetching finalized/latest block of Optimism node
    # Optional, default value: 1000ms
    interval_ms = 4000

    ##############################################
    # Mach scheduler configuration               #
    ##############################################:
    [scheduler]
    # The timeout waiting for verify result.
    # If it times out, the verify result will be checked again in the next tick.
    # Optional, default value: 100ms
    verify_timeout_ms = 100

# SECRETS
secrets:
  # if false, use existing secret
  create: true
  # secret name
  bls-key: "MY-BLS-KEY-SECRET"
  bls-key-password: "MY-BLS-KEY-PASSWORD-SECRET"
