apiVersion: v1
kind: Service
metadata:
  name: {{ include "karak.fullname" . }}
  annotations:
    {{- tpl (toYaml .Values.service.annotations | nindent 4) $ }}
  labels:
    {{- include "karak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    {{- include "karak.selectorLabels" . | nindent 4 }}