apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "witnesschain-watchtower.fullname" . }}
  labels:
    {{- include "witnesschain-watchtower.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config-without-key.json: >-
    {{- .Values.clientConfig.json | nindent 4 }}