apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "witnesschain-watchtower.fullname" . }}
  labels:
    {{- include "witnesschain-watchtower.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "witnesschain-watchtower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "witnesschain-watchtower.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "witnesschain-watchtower.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-client-config
          image: apteno/alpine-jq:latest
          command:
            - sh
            - -c
            - |
              key=$(cat /app/secret/key) &&
              jq --arg key "$key" ". + {private_key: \$key}" /app/config/config-without-key.json > /watchtower/src/client/config.json
          volumeMounts:
            - name: init-config
              mountPath: /app/config
            - name: init-secret
              mountPath: /app/secret
            - name: client-config
              mountPath: /watchtower/src/client
      containers:
        - name: {{ include "witnesschain-watchtower.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: client-config
              mountPath: /watchtower/src/client/config.json
              subPath: config.json
              readOnly: true
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: init-config
          configMap:
            name: {{ include "witnesschain-watchtower.fullname" . }}
        - name: init-secret
          secret:
            secretName: {{ .Values.secretNames.watchtowerKey }}
        - name: client-config
          emptyDir: {}
