apiVersion: v1
kind: Service
metadata:
  name: {{ include "witnesschain-watchtower.fullname" . }}-headless
  labels:
    {{- include "witnesschain-watchtower.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "witnesschain-watchtower.selectorLabels" . | nindent 4 }}
