apiVersion: v1
kind: Service
metadata:
  name: {{ include "witnesschain-watchtower.fullname" . }}
  labels:
    {{- include "witnesschain-watchtower.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end -}}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    {{- range $port := .Values.service.ports }}
    - name: port-{{ $port }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
  selector:
    {{- include "witnesschain-watchtower.selectorLabels" . | nindent 4 }}