apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lagrange-state-committees.fullname" . }}-config
  labels:
    {{- include "lagrange-state-committees.labels" . | nindent 4 }}
data:
  client.toml: |-
    {{ .Values.clientConfig | nindent 4 }}