apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagrange-state-committees.fullname" . }}
  labels:
    {{ include "lagrange-state-committees.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lagrange-state-committees.selectorLabels" . | nindent 6 }}
      {{- with .Values.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end}}
  template:
    metadata:
      labels:
        app: {{ include "lagrange-state-committees.fullname" . }}
        {{- include "lagrange-state-committees.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
    spec:
      serviceAccountName: {{ include "lagrange-state-committees.serviceAccountName" . }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
      - name: lagrange-state-committees
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.prometheusPort }}
        volumeMounts:
        - name: client-config
          mountPath: /app/config/client.toml
          subPath: client.toml
        - name: bls-keystore
          mountPath: /app/config/keystore/bls.json
          subPath: keystore.json
        - name: bls-keystore-pass
          mountPath: /app/config/keystore/bls.pass
          subPath: password
        - name: signer-keystore
          mountPath: /app/config/keystore/signer.json
          subPath: keystore.json
        - name: signer-keystore-pass
          mountPath: /app/config/keystore/signer.pass
          subPath: password
        command: ["/bin/sh", "-c", "/app/lagrange-node run-client -c /app/config/client.toml"]
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
      volumes:
      - name: client-config
        configMap:
          name: {{ include "lagrange-state-committees.fullname" . }}-config
      - name: bls-keystore
        secret:
          secretName: {{ .Values.secrets.blsKey }}
      - name: bls-keystore-pass
        secret:
          secretName: {{ .Values.secrets.blsKeyPassword }}
      - name: signer-keystore
        secret:
          secretName: {{ .Values.secrets.signerKey }}
      - name: signer-keystore-pass
        secret:
          secretName: {{ .Values.secrets.signerKeyPassword }}
