apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagrange-state-committees.fullname" . }}
  labels:
    {{ include "lagrange-state-committees.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "lagrange-state-committees.selectorLabels" . | nindent 4 }}