apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagrange-state-committees.fullname" . }}
  labels:
    {{ include "lagrange-state-committees.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "lagrange-state-committees.name" . }}
