replicaCount: 1
labels: {}
commonLabels: {}
nodeSelector: {}
tolerations: []
affinity: {}
# Use keel instead of the watchtower container
annotations:
  keel.sh/policy: all
  keel.sh/trigger: poll
  keel.sh/pollSchedule: "@every 60s"

resources: {}

service:
  type: ClusterIP
  headlessPorts:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics

metricsPort: 9090

serviceAccount:
  create: false
  name: ""

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 1m
  scrapeTimeout: 30s

network: holesky


secrets:
  ecdsaKeystorePassword: ""
  ecdsaKeystore: ""

image:
  repository: lagrangelabs/worker
  tag: holesky # This should be the same as the network
  pullPolicy: IfNotPresent

worker:
  environment:
    RUST_LOG: "info,worker=debug"
    PUBLIC_PARAMS__SKIP_STORE: "false"
    RPC_URL: "https://ethereum-holesky-rpc.publicnode.com"
  # Do not change this config file except for the gateway_url (which differs for each network)
  configToml: |
    [worker]
    data_dir = "/tmp"
    instance_type = "medium"
    [avs]
    gateway_url = "ws://gateway.test-distributed-query.test.distributed-query.io:80"
    issuer = "lagrange"
    worker_id = "generic-worker"
    [prometheus]
    port = 9090

persistence:
  zkmr_params:
    enabled: true
    size: 20Gi
    storageClass: local-path
