{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arpa.fullname" . }}-exporter
  labels:
    {{- include "arpa.labels" . | nindent 4 }}
    app: {{ include "arpa.name" . }}-exporter
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "arpa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arpa.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ include "arpa.name" . }}-exporter
    spec:
      containers:
        - name: {{ .Chart.Name }}-exporter
          resources: 
            limits:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: "2Gi"
            requests:
              cpu: 100m
              memory: 128Mi
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - name: exporter-http
              containerPort: {{ .Values.exporter.config.exporter_port }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/exporter-config.yml
              subPath: exporter-config.yml
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.exporter.config.exporter_port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.exporter.config.exporter_port }}
            initialDelaySeconds: 3
            periodSeconds: 3

      volumes:
        - name: config-volume
          configMap:
            name: {{ include "arpa.fullname" . }}-exporter-config
      automountServiceAccountToken: false
{{- end }}