apiVersion: v1
kind: Service
metadata:
  name: {{ include "arpa.name" . }}-external
  labels:
    {{- include "arpa.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
{{- range .Values.externalService.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
{{- end }}
{{- if .Values.externalService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.externalService.loadBalancerIP }}
{{- end }}
  selector:
    app: {{ include "arpa.name" . }}
