apiVersion: v1
kind: Service
metadata:
  name: {{ include "arpa.name" . }}-internal
  labels:
    {{- include "arpa.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
{{- range .Values.internalService.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
{{- end }}
  selector:
    app: {{ include "arpa.name" . }}
