{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecrets.arpaNodeKey.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    keystore: {{ .Values.sealedSecrets.arpaNodeKey.encryptedData.keystore }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecrets.arpaNodeKeyPassword.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: {{ .Values.sealedSecrets.arpaNodeKeyPassword.encryptedData.password }}
{{- end }}