{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretNames.arpaNodeKey }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    keystore: {{ .Values.sealedSecrets.arpaNodeKey.encryptedData.keystore }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretNames.arpaNodeKeyPassword }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: {{ .Values.sealedSecrets.arpaNodeKeyPassword.encryptedData.password }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretNames.arpaAwsSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
{{- range $key, $value := .Values.sealedSecrets.arpaAwsSecret.encryptedData }}
    "{{ $key }}": {{ $value }}
{{- end }}
{{- end }}