{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "arpa.fullname" . }}
  labels:
    {{- include "arpa.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  {{- range .Values.serviceMonitor.ports }}
    - port: {{ .port }}
      path: {{ .path }}
      interval: {{ .interval }}
      scrapeTimeout: {{ .scrapeTimeout }}
      honorLabels: true
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- . | nindent 8 }}
      {{- end }}
      relabelings:
      {{- range $key, $value := .Values.commonLabels }}
      - action: replace
        targetLabel: {{ $key | trimPrefix "a41.io/" | quote }}
        replacement: {{ $value | quote }}
      {{- end }}
  {{- end }}
  {{- if .Values.exporter.enabled }}
    - port: {{ .Values.exporter.serviceMonitor.port }}
      path: {{ .Values.exporter.serviceMonitor.path }}
      interval: {{ .Values.exporter.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.exporter.serviceMonitor.scrapeTimeout }}
      honorLabels: true
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- . | nindent 8 }}
      {{- end }}
      relabelings:
      {{- range $key, $value := .Values.commonLabels }}
      - action: replace
        targetLabel: {{ $key | trimPrefix "a41.io/" | quote }}
        replacement: {{ $value | quote }}
      {{- end }}
  {{- end }}
  jobLabel: {{ .Release.Name }}
  selector:
    matchLabels:
      {{- include "arpa.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end -}}