apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eigenda.fullname" . }}-policy
  labels:
    {{- include "eigenda.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "eigenda.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}