apiVersion: v1
kind: Service
metadata:
  name: {{ include "eigenda.fullname" . }}
  annotations:
    {{- tpl (toYaml .Values.service.annotations | nindent 4) $ }}
  labels:
    {{- include "eigenda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: retrieval
      port: {{ .Values.retrievalPort }}
      protocol: TCP
      targetPort: retrieval
    - name: dispersal
      port: {{ .Values.dispersalPort }}
      protocol: TCP
      targetPort: dispersal
    - name: v2-retrieval
      port: {{ .Values.v2RetrievalPort }}
      protocol: TCP
      targetPort: v2-retrieval
    - name: v2-dispersal
      port: {{ .Values.v2DispersalPort }}
      protocol: TCP
      targetPort: v2-dispersal
  selector:
    {{- include "eigenda.selectorLabels" . | nindent 4 }}
