apiVersion: v1
kind: Service
metadata:
  name: {{ include "eigenda.fullname" . }}
  labels:
    {{- include "eigenda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  {{- if .Values.ports }}
    {{ toYaml .Values.ports | nindent 4}}
  {{- end }}
  selector:
    {{- include "eigenda.selectorLabels" . | nindent 4 }}
