apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eigenda.fullname" . }}
  labels:
    {{- include "eigenda.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "eigenda.fullname" . }}
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        storageClassName: {{ .Values.persistence.storageClassName }}
  selector:
    matchLabels:
      {{- include "eigenda.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "eigenda.fullname" . }}
        {{- include "eigenda.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-srs
          volumeMounts:
            - name: data
              mountPath: /data
        {{- toYaml .Values.initContainers.initSrs | nindent 10 }}
        {{- if .Values.initContainers.updateSocket.enabled }}
        - name: update-socket
          image: {{ .Values.initContainers.updateSocket.image.repository }}:{{ .Values.initContainers.updateSocket.image.tag }}
          volumeMounts:
            - name: bls-keystore
              mountPath: /app/.eigenlayer/operator_keys/bls.key.json
              subPath: keystore.json
            {{- if .Values.secrets.ecdsaKeystore }}
            - name: ecdsa-keystore
              mountPath: /app/.eigenlayer/operator_keys/ecdsa.key.json
              subPath: keystore.json
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "eigenda.fullname" . }}-node-env
          env:
            - name: NODE_OPERATION
              value: "update-socket"
            - name: NODE_SOCKET
              value: "$(NODE_HOSTNAME):$(NODE_DISPERSAL_PORT);$(NODE_RETRIEVAL_PORT)"
            - name: NODE_BLS_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.blsKeystorePassword }}
                  key: password
            {{- if .Values.secrets.ecdsaKeystore }}
            - name: NODE_ECDSA_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.ecdsaKeystorePassword }}
                  key: password
            {{- end }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eigenda.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: node
          {{- with .Values.node.args }}
          args:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.node.securityContext | nindent 12 }}
          image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}"
          imagePullPolicy: {{ .Values.node.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.dispersalPort }}
            protocol: TCP
            name: dispersal
          - containerPort: {{ .Values.internalRetrievalPort }}
            protocol: TCP
            name: int-retrieval
          - containerPort: {{ .Values.metricsPort }}
            protocol: TCP
            name: metrics
          {{- if .Values.node.lifecycleHooks }}
          lifecycle:
          {{- toYaml .Values.node.lifecycleHooks | nindent 12 }}
          {{- end }}
          startupProbe:
            httpGet:
              path: /eigen/node/health
              port: {{ .Values.internalApiPort }}
            {{- with .Values.node.startupProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /eigen/node/health
              port: {{ .Values.internalApiPort }}
            {{- with .Values.node.readinessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /eigen/node/health
              port: {{ .Values.internalApiPort }}
            {{- with .Values.node.livenessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: bls-keystore
              mountPath: /app/.eigenlayer/operator_keys/bls.key.json
              subPath: keystore.json
            {{- if .Values.secrets.ecdsaKeystore }}
            - name: ecdsa-keystore
              mountPath: /app/.eigenlayer/operator_keys/ecdsa.key.json
              subPath: keystore.json
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "eigenda.fullname" . }}-node-env
          env:
            - name: NODE_BLS_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.blsKeystorePassword }}
                  key: password
            {{- if .Values.secrets.ecdsaKeystore }}
            - name: NODE_ECDSA_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.ecdsaKeystorePassword }}
                  key: password
            {{- end }}
          {{- if .Values.node.env }}
            {{- toYaml .Values.node.env | nindent 12 }}
          {{- end }}
        - name: proxy
          {{- with .Values.proxy.command }}
          command:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.args }}
          args:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.proxy.securityContext | nindent 12 }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.retrievalPort }}
            protocol: TCP
            name: retrieval
          - containerPort: {{ .Values.internalApiPort }}
            protocol: TCP
            name: api
          {{- if .Values.proxy.lifecycleHooks }}
          lifecycle:
          {{- toYaml .Values.proxy.lifecycleHooks | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.startupProbe }}
          startupProbe:
          {{- toYaml .Values.proxy.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.proxy.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.proxy.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: rate-limit-nginx.conf
          envFrom:
            - configMapRef:
                name: {{ include "eigenda.fullname" . }}-proxy-env
          {{- if .Values.proxy.env }}
          env:
            {{- toYaml .Values.proxy.env | nindent 12 }}
          {{- end }}
      volumes:
        - name: proxy-config
          configMap:
            name: {{ include "eigenda.fullname" . }}-proxy-config
        - name: bls-keystore
          secret:
            secretName: {{ .Values.secrets.blsKeystore }}
        {{- if .Values.secrets.ecdsaKeystore }}
        - name: ecdsa-keystore
          secret:
            secretName: {{ .Values.secrets.ecdsaKeystore }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}