apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eigenda.fullname" . }}
  labels:
    {{- include "eigenda.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
spec:
  serviceName: {{ include "eigenda.fullname" . }}
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        storageClassName: {{ .Values.persistence.storageClassName }}
  selector:
    matchLabels:
      {{- include "eigenda.selectorLabels" . | nindent 6 }}
      {{- with .Values.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "eigenda.fullname" . }}
        {{- include "eigenda.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eigenda.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: node
          {{- with .Values.node.args }}
          args:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.node.image.pullPolicy }}
          ports:
          {{- toYaml .Values.node.ports | nindent 10 }}
          {{- if .Values.lifecycleHooks }}
          lifecycle:
          {{- toYaml .Values.node.lifecycleHooks | nindent 12 }}
          {{- end }}
          {{- if .Values.node.startupProbe }}
          startupProbe:
          {{- toYaml .Values.node.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.node.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.node.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.node.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.node.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: bls-keystore
              mountPath: /app/.eigenlayer/operator_keys/bls.key.json
              subPath: keystore.json
              readOnly: true
            - name: ecdsa-keystore
              mountPath: /app/.eigenlayer/operator_keys/ecdsa.key.json
              subPath: keystore.json
              readOnly: true
          envFrom:
            - configMapRef:
                name: node-env
          env:
            - name: NODE_BLS_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.blsKeyPassword }}
                  key: password
            - name: NODE_ECDSA_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.ecdsaKeyPassword }}
                  key: password
        - name: proxy
          {{- with .Values.proxy.command }}
          command:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.args }}
          args:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
          {{- toYaml .Values.proxy.ports | nindent 10 }}
          {{- if .Values.lifecycleHooks }}
          lifecycle:
          {{- toYaml .Values.proxy.lifecycleHooks | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.startupProbe }}
          startupProbe:
          {{- toYaml .Values.proxy.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.proxy.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.proxy.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          volumeMounts:
            - name: proxy-config
              mountPath: /config/rate-limit-nginx.conf
              subPath: rate-limit-nginx.conf
            - name: data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: proxy-env
      volumes:
        - name: proxy-config
          configMap:
            name: {{ include "eigenda.fullname" . }}-proxy-config
        - name: proxy-env
          configMap:
            name: {{ include "eigenda.fullname" . }}-proxy-env
        - name: node-env
          configMap:
            name: {{ include "eigenda.fullname" . }}-node-env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}