# Default values for eoracle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eoracle/data-validator
  pullPolicy: IfNotPresent
  tag: "v0.1.8"

## Common labels
##
commonLabels: {}

## Network to which the client is connected
network: holesky

env:
  EO_CHAIN_RPC_ENDPOINT: https://rpc.testnet.eoracle.network
  EO_CHAIN_WS_ENDPOINT: wss://rpc.testnet.eoracle.network/ws
  EO_REGISTRY_COORDINATOR: "0xc4A6E362e8Bd89F28Eb405F9Aa533784884B9c4F"
  EO_STAKE_REGISTRY: "0xdda1a381920971642477CA79F5BFc1515414782d"
  EO_AGGREGATOR_ADDRESS: "0x6B0BE2aaD42612803c9Fc389A3806EF21E8cbDb6"
  EO_CONFIG_ADDRESS: "0xf735Ad57952906a672eEEaDbef3bC69ECD24E50C"
  ETH_RPC_ENDPOINT: http://eth-rpc.a41.io/holesky
  ETHEREUM_FEED_RPC_ENDPOINT: http://eth-rpc.a41.io/holesky
  EO_KEYSTORE_PATH: .keystore
  EO_PROMETHEUS_PORT: "10004"
  EO_HEALTH_ENDPOINTS_PORT: "10003"
  EO_LOGGING_LEVEL: info

secrets:
  blsKey: ""
  ecdsaAliasedKey: ""
  passphrase: ""


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

## Service monitor to use
##
serviceMonitor:
  # If true, create a serviceMonitor
  enabled: true
  # Annotations
  annotations: {}
  # Path to scrape
  path: /metrics
  # Scrape interval
  interval: 1m
  # Scrape timeout
  scrapeTimeout: 30s

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# securityContext:
#   runAsUser: 65534
#   runAsGroup: 65534


service: {}
resources: {}

livenessProbe:
  httpGet:
    path: /metrics
    port: metrics
readinessProbe:
  httpGet:
    path: /metrics
    port: metrics

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
