# Default values for eoracle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eoracle/data-validator
  pullPolicy: IfNotPresent
  tag: "v0.1.8"

env:
  EO_OPERATOR_CLI_IMAGE: eoracle/opr_cli:v0.0.12
  EO_CHAIN_RPC_ENDPOINT: https://rpc.eoracle.network
  EO_CHAIN_WS_ENDPOINT: wss://rpc.eoracle.network/ws
  EO_REGISTRY_COORDINATOR: "0x757E6f572AfD8E111bD913d35314B5472C051cA8"
  EO_STAKE_REGISTRY: "0x761DF0e99160a4bd19391475D2a1101eaab20F24"
  EO_AGGREGATOR_ADDRESS: "0x4E70004b01987B4fd7DAcab348F0B39E9AE26110"
  EO_CONFIG_ADDRESS: "0x05a6f762f64Ac2ccE0588677317a0Ed8af9d0c16"
  ETH_RPC_ENDPOINT: https://eth-mainnet.g.alchemy.com/v2/wGZwmC7PkgnKawXtigCcvzKmZFETYT1F
  ETHEREUM_FEED_RPC_ENDPOINT: https://eth-mainnet.g.alchemy.com/v2/wGZwmC7PkgnKawXtigCcvzKmZFETYT1F
  EO_KEYSTORE_PATH: /app/.keytore
  EO_PROMETHEUS_PORT: "10004"
  EO_HEALTH_ENDPOINTS_PORT: "10003"
  EO_LOGGING_LEVEL: info

secrets:
  blsKey: ""
  ecdsaAliasedKey: ""
  ecdsaKey: ""
  passphrase: ""


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# securityContext:
#   runAsUser: 65534
#   runAsGroup: 65534


service: {}
resources: {}

livenessProbe:
  httpGet:
    path: /metrics
    port: metrics
readinessProbe:
  httpGet:
    path: /metrics
    port: metrics

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
