# Test using Holesky + mock srs config

# Github Action Runner resource limits: https://docs.github.com/ko/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for--private-repositories
# CPU: 2-core, Memory: 7 GB, Disk: 14 GB
# Kube System Uses: 950m CPU, 290Mi Memory
# Available for Helm Test: 1050m CPU, 6.71Gi Memory

node:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  env:
    - name: NODE_SRS_ORDER
      value: "3000"
    - name: NODE_SRS_LOAD
      value: "3000"
  startupProbe:
    initialDelaySeconds: 20   # reduce initial delay for faster test

proxy:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi

serviceMonitor:
  enabled: false

network: holesky

ethRpcUrl: "https://ethereum-holesky-rpc.publicnode.com"

persistence:
  size: 10Gi
  storageClassName: "standard"  # use default storage class

service:
  type: ClusterIP

initContainers:
  updateSocket:
    enabled: false
  # mock srs setup for test
  initSrs:
    command:
      - sh
      - -c
      - |
        G1="/data/g1.point"
        G2="/data/g2.point.powerOf2"
        if [ ! -f "$G1" ] || [ ! -f "$G2" ]; then
          apk add --no-cache git;
          mkdir -p /data/logs && mkdir -p /data/operator/db;
          git clone https://github.com/Layr-Labs/eigenda.git;
          cd eigenda;
          mv ./inabox/resources/kzg/g1.point $G1;
          mv ./inabox/resources/kzg/g2.point.powerOf2 $G2;
        else
          echo "SRS exists, skipping setup";
        fi;

secrets:
  blsKeystore: "dummy-bls-keystore"
  blsKeystorePassword: "dummy-bls-password"
