apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eoracle.fullname" . }}-vmagent-config
  labels:
    {{- include "eoracle.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  vmagent.yml: |
    global:
      scrape_interval: {{ .Values.vmagent.scrapeInterval }}
      
    scrape_configs:
      - job_name: 'eoracle-data-validator'
        static_configs:
          - targets: ['localhost:{{ .Values.env.EO_PROMETHEUS_PORT }}']
        metric_relabel_configs:
        - target_label: operator_address
          replacement: {{ .Values.operatorAddress }}
        - target_label: eochain
          replacement: {{ .Values.network }}