apiVersion: v1
kind: Service
metadata:
  name: {{ include "eoracle.fullname" . }}
  labels:
    {{- include "eoracle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.env.EO_PROMETHEUS_PORT }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.env.EO_HEALTH_ENDPOINTS_PORT }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.vmagent.containerPort }}
      targetPort: vmagent
      protocol: TCP
      name: vmagent
  selector:
    {{- include "eoracle.selectorLabels" . | nindent 4 }}
    