replicaCount: 1

image:
  repository: lagrangelabs/lagrange-node
  pullPolicy: IfNotPresent
  tag: "{{ .Values.version }}"

service:
  type: ClusterIP
  port: 8080

prometheusPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: ""

env:
  Network: "mainnet"
  ChainName: "ethereum"
  Version: "latest"
  PrometheusPort: "8080"
  ClientConfigFilePath: "/path/to/client.toml"
  BLSKeystorePath: "/path/to/bls.key"
  BLSKeystorePasswordPath: "/path/to/bls.pass"
  SignerECDSAKeystorePath: "/path/to/signer.key"
  SignerECDSAKeystorePasswordPath: "/path/to/signer.pass"
  ServerGrpcURL: "grpc.server.url"
  EthereumRPCURL: "https://mainnet.infura.io/v3/YOUR-PROJECT-ID"
  OperatorAddress: "0xYourOperatorAddress"
  CommitteeSCAddress: "0xYourCommitteeSCAddress"
  L2RPCEndpoint: "https://l2.rpc.endpoint"
  L1RPCEndpoint: "https://l1.rpc.endpoint"
  BeaconURL: "https://beacon.url"
  BatchInbox: "0xBatchInboxAddress"
  BatchSender: "0xBatchSenderAddress"
