replicaCount: 1

image:
  repository: lagrangelabs/lagrange-node
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

prometheusPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: ""

env:
  Network: "mainnet"
  ChainName: "ethereum"
  Version: "latest"
  PrometheusPort: "8080"
  ServerGrpcURL: "grpc.server.url"
  EthereumRPCURL: "https://mainnet.infura.io/v3/YOUR-PROJECT-ID"
  OperatorAddress: "0xYourOperatorAddress"
  CommitteeSCAddress: "0xYourCommitteeSCAddress"
  L2RPCEndpoint: "https://l2.rpc.endpoint"
  L1RPCEndpoint: "https://l1.rpc.endpoint"
  BeaconURL: "https://beacon.url"
  BatchInbox: "0xBatchInboxAddress"
  BatchSender: "0xBatchSenderAddress"

secrets:
  blsKey: "mainnet-bls-key"
  blsKeyPassword: "mainnet-bls-key-password"
  ecdsaKey: "mainnet-ecdsa-key"
  ecdsaKeyPassword: "mainnet-ecdsa-key-password"
