{{- if and (.Values.zenrock.persistence.enabled) (not .Values.zenrock.persistence.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-data" (include "zenrock.fullname" .) }}
  labels:
    {{- include "zenrock.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zenrock.persistence.size }}
  storageClassName: {{ .Values.zenrock.persistence.storageClass }}
  selector:
    {{- include "zenrock.selectorLabels" . | nindent 4 }}
{{- end }}
